DROP TABLE PASSAGEIRO;

CREATE TABLE PASSAGEIRO
(
    ID_PASSAGEIRO INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(30) NOT NULL
);

DROP TABLE LINHA;

CREATE TABLE LINHA
(
    ID_LINHA INTEGER NOT NULL PRIMARY KEY,
    ID_PASSAGEIRO INTEGER NOT NULL,
    PARTIDA VARCHAR(50),
    DESTINO VARCHAR(50),

    CONSTRAINT FK_PASSAGEIRO FOREIGN KEY (ID_PASSAGEIRO) REFERENCES PASSAGEIRO (ID_PASSAGEIRO)
);

DROP TABLE ONIBUS;

CREATE TABLE ONIBUS
(
    ID_ONIBUS INTEGER NOT NULL PRIMARY KEY,
    ID_LINHA INTEGER NOT NULL,
    PLACA VARCHAR(6) NOT NULL,

    CONSTRAINT FK_LINHA FOREIGN KEY (ID_LINHA) REFERENCES LINHA (ID_LINHA)
);

DROP TABLE MOTORISTA;

CREATE TABLE MOTORISTA
(
    ID_MOTORISTA INTEGER NOT NULL PRIMARY KEY,
    ID_ONIBUS INTEGER NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    
    CONSTRAINT FK_ONIBUS FOREIGN KEY (ID_ONIBUS) REFERENCES ONIBUS (ID_ONIBUS)
);


